name: GameGenie
main: com.minecarts.gamegenie.GameGenie
version: ${pom.version}
website: http://minecarts.com
author: Verrier
description: >
             A quick game mode switcher
commands:
    gm:
        aliases: [gamemode]
        description: Quickly switch a player or multiple players game mode
        usage: "/<command> [name, ...]"
permissions:
    gamegenie.toggle:
        description: "Access to toggle the gamemode on a list of players"
        default: op
    gamegenie.allowdrop:
        description: "Allow users to drop items in creative mode"
        default: op
    gamegenie.bypasswipe:
        description: "When switching modes your inventory is wiped"
        default: false