name: GameGenie
description: A quick game mode switcher
author: verrier, megabytes
website: http://minecarts.com/

main: com.minecarts.gamegenie.GameGenie
version: ${pom.version}

commands:
    gamegenie:
        aliases: [gg, gm]
        description: Quickly switch a player or multiple players game mode
        usage: "/<command> [list | name, ...]"
        
permissions:
    gamegenie.toggle:
        description: "Access to toggle the gamemode on a list of players"
        default: op
    gamegenie.bypass.drop:
        description: "Allow users to drop items in creative mode"
        default: op
    gamegenie.bypass.wipe:
        description: "When switching modes your inventory is wiped"
        default: false
    gamegenie.notify:
        description: "Get notified when someone changes the gamemode for another player"
        default: op
    gamegenie.blacklist:
        description: "Prevents this player from being put in creative mode"
        default: false
    gamegenie.bypass.container:
        description: "Bypass the container in creative mode restrictions"
        default: op